/**
 * scripts/build-vercel.mjs
 * Vercel 构建脚本 — 合并 jowork/public + root public，输出到 dist/public
 *
 * 层叠规则：
 *   1. 先复制 root/public/（基础 UI：admin.html, chat.html, dashboard.html 等）
 *   2. 再覆盖 apps/jowork/public/（JoWork 专属页面：shell.html, onboarding.html 等）
 */

import { cpSync, mkdirSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot  = resolve(__dirname, '..');               // apps/jowork/
const repoRoot = resolve(__dirname, '../../..');         // monorepo root
const outDir   = resolve(appRoot, 'dist/public');

// 清理并创建输出目录
mkdirSync(outDir, { recursive: true });

// 1. 复制 root public/（基础 UI）
const rootPublic = resolve(repoRoot, 'public');
if (existsSync(rootPublic)) {
  cpSync(rootPublic, outDir, { recursive: true });
  console.log(`✓ Copied root public/ → dist/public/`);
} else {
  console.warn('⚠ root public/ not found, skipping');
}

// 2. 覆盖 jowork-specific public/（优先级更高）
const joworkPublic = resolve(appRoot, 'public');
if (existsSync(joworkPublic)) {
  cpSync(joworkPublic, outDir, { recursive: true });
  console.log(`✓ Overlaid apps/jowork/public/ → dist/public/`);
}

// 3. 写入 runtime-config.js 模板（Vercel 部署时由用户在 Dashboard 配置）
//    前端通过 window.__JOWORK_GATEWAY_URL__ 读取后端地址
const runtimeConfig = `
// JoWork Runtime Configuration
// This file is auto-generated by the Vercel build process.
// Set JOWORK_BACKEND_URL in Vercel Dashboard → Settings → Environment Variables
// to point to your self-hosted JoWork Gateway.
window.__JOWORK_GATEWAY_URL__ = "${process.env.JOWORK_BACKEND_URL || ''}";
`;
writeFileSync(resolve(outDir, 'runtime-config.js'), runtimeConfig.trim() + '\n');
console.log(`✓ Generated runtime-config.js`);

console.log(`\n✓ Vercel build complete → ${outDir}`);
console.log(`  Configure JOWORK_BACKEND_URL in Vercel to point to your gateway.`);
